### ISSUE TITLE
Tricky api in (Persistent)Proces

### ISSUE THREAD

**Issue by rwiskerke** [jgordijn/process#21]
Both `PersistenProcess` and `Process` traits have the abstract 

``` scala
 def process: ProcessStep[State]
```

This has the distinct disadvantage that when implementing this trait you have the option to define a function which returns a different object each time, which is not what you would expect. 

Let just change it to:

``` scala
 val process: ProcessStep[State]
```

@jgordijn what do you think?

**Comment by jgordijn** [comment]
Yes, that sounds absolutely reasonable. Defining a new proces every time can lead to real tricky bugs. Please feel free to create a PR.

**Comment by jgordijn** [comment]
This is now fixed by @rwiskerke PR. I also created a new release:  [0.1.18](https://github.com/jgordijn/process/releases/tag/v0.1.18)
