### ISSUE TITLE
Release to maven central and include in scalaindex

### ISSUE THREAD

**Issue by ktoso** [jgordijn/process#25]
Hi there :)
Though we never had the time to deep dive into it I think this is a very nice project - how about releasing it to maven central and also making sure it shows up in https://index.scala-lang.org/search?q=process ?

We nowadays have a new community page which defers all search to scaladex so this way people would find this library. http://akka.io/community/

**Comment by jgordijn** [comment]
Thanks for getting in touch. I will make sure to do that.

**Comment by jgordijn** [comment]
It is now included in https://index.scala-lang.org/search?q=process and on maven central.
